apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobhub-deployment
  labels:
    app: jobhub

spec:
  replicas: 2
  selector:
    matchLabels:
      app: jobhub

  template:
    metadata:
      labels:
        app: jobhub

    spec:
      containers:
      - name: jobhub-container
        image: 88653/linkdin:v1
        ports:
        - containerPort: 80
